// <auto-generated />
namespace RetailApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DbSetInventory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbSetInventory));
        
        string IMigrationMetadata.Id
        {
            get { return "201903251632075_DbSetInventory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
